# Generated by Django 3.1.6 on 2021-02-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_thoughts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='Thought',
        ),
    ]
