# Generated by Django 3.1.6 on 2021-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210221_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='description_field',
            field=models.CharField(default='Description', max_length=300),
        ),
    ]
